spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fitness?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USER:dev}
    password: ${DB_PASS:dev}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    validate-migration-naming: true
    locations: classpath:db/migration

logging:
  level:
    org.flywaydb: INFO
    org.springframework.security: DEBUG
    com.brigi.backend.security: DEBUG # Add your security package
    org.springframework.web: DEBUG # Add web debugging
    org.springframework.security.web.FilterChainProxy: DEBUG # Add filter chain debugging
    com.brigi.backend: DEBUG # Add this line to enable debug for your package
    com.brigi.backend.controller: DEBUG # Specific for controllers

app:
  jwtSecret: "VlRxNq6mNgKx8GNzzJ9MBsVUHjqO8tBQ3fvmayorufqaviI7blarZ+14WlwUSHT7"
  jwtTtlMinutes: 43200

strava:
  clientId: "YOUR_STRAVA_CLIENT_ID"
  clientSecret: "YOUR_STRAVA_CLIENT_SECRET"
  redirectUri: "http://localhost:8080/api/v1/oauth/strava/callback"
  scope: "read,activity:read_all"
